#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

python3 ~/dev/scripts/sweet-startup.py

export PATH=$PATH:/home/tori/.spicetify
